### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by eouia** [rvowles/node-assistant#6]
After `node index` I've got this error. How can I fix?
```
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libcblas.so.3: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/node-assistant/node_modules/snowboy/lib/node/index.js:8:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by rvowles** [comment]
No idea - looks like an error in Snowboy - I recommend you ask over there.
